### ISSUE TITLE
Use of projectname.min.js

### ISSUE THREAD

**Issue by jdeisenberg** [swannodette/mies#13]
I could not find any place in the documentation that explained how to use the *projectname*.min.js file that `lein cljsbuild once` creates. Here is some possible documentation:

When you build the project, you will end up with these two files:  <code><i>projectname</i>.js</code> and <code><i>projectname</i>.min.js</code>. The build process creates an `index.html` file that references <code><i>projectname</i>.js</code>. If you want to use the minimized file, change the lines in `index.html` as follows:

<pre>&lt;script src="out/goog/base.js" type="text/javascript"&gt;&lt;/script&gt;
&lt;script src="<i>projectname</i>.min.js" type="text/javascript"&gt;&lt;/script&gt;
&lt;!--&lt;script type="text/javascript"&gt;goog.require("<i>projectname</i>.core");&lt;/script&gt;--&gt;</pre>

Also: what is the advantage of using <code><i>projectname</i>.min.js</code>?

**Comment by swannodette** [comment]
@jdeisenberg it's just a JavaScript convention. It's an oversight not to provide an html page for the release version.

**Comment by swannodette** [comment]
Fixed in master
