### ISSUE TITLE
scripts/brepl does not want to connect

### ISSUE THREAD

**Issue by jdeisenberg** [swannodette/mies#18]
Created a new project with latest version of mies template. Uncommented the line:
```` (repl/connect "http://localhost:9000/repl")````

Then did this in a terminal window: 
````
[david@localhost testor]$ scripts/brepl
Compiling client js ...
Waiting for browser to connect ...
To quit, type: :cljs/quit
````

Went into the browser to http://localhost:9000 and the index.html page came up, but the terminal window did not give me a browser REPL prompt. What am I doing wrong? (I also notice that `lein-cljsbuild` is no longer part of mies's universe)

**Comment by bensu** [comment]
Which version are you using, the one in Clojars ? In that one, `0.5.3`, you need `lein-cljsbuild auto` running to get the `brepl`. I had the same issue when I was using the Clojars version but reading the new README from this repo. It might be that.

**Comment by jdeisenberg** [comment]
Yes, that seems to be the solution. I was using mies 0.6.0, IIRC.
