### ISSUE TITLE
cljsbuild is not a task?

### ISSUE THREAD

**Issue by jdeisenberg** [swannodette/mies#19]
I did a local install by cloning the repository and then doing `lein install` followed by this:

````
[david@localhost ~]$ mkdir mtest
[david@localhost ~]$ cd mtest
[david@localhost mtest]$ lein new mies m060
[david@localhost mtest]$ cd m060
[david@localhost m060]$ lein cljsbuild auto
'cljsbuild' is not a task. See 'lein help'.
````

**Comment by jdeisenberg** [comment]
Note: I'm using `lein cljsbuild auto` as per the README.md. This may not be an issue any more given https://github.com/clojure/clojurescript/wiki/Reporting-Issues

**Comment by swannodette** [comment]
@jdeisenberg yes the intention is to remove cljsbuild from mies entirely.

**Comment by alancwoo** [comment]
I hate to bump an old issue, and then refer to an old post, but I was trying out your 'clojurescript 101' article and received the same error above on `lein cljsbuild auto async-tut1`. What would be the correct way to run this tutorial now? Apologies if this isn't the ideal venue for this question.

**Comment by bensu** [comment]
@alancwoo  I think you are looking for `./scripts/watch`. This will trigger the Clojure code under `scripts/watch.clj` that starts the compiler in auto watch mode.

For context, read [Quick Start](https://github.com/clojure/clojurescript/wiki/Quick-Start).

**Comment by alancwoo** [comment]
@bensu Thanks for the info, unfortunately now I'm getting `Exception in thread "main" java.io.FileNotFoundException: Could not locate cljs/build/api__init.class or cljs/build/api.clj on classpath:`
