### ISSUE TITLE
scripts/build does not exist

### ISSUE THREAD

**Issue by pate** [swannodette/mies#28]
Is README out of date?

I followed the instructions to make a new project with `lein new mies hello-world`, but in that folder `scripts/build` does not exist.

**Comment by bensu** [comment]
The last version `0.6.0` in master, which is consistent with the README has not been deployed to Clojars yet. Try:

git clone https://github.com/swannodette/mies
cd mies
lein install
cd ..
lein new mies hello-world

And you'll get a copy of the latest mies template.

**Comment by kaosbeat** [comment]
had the same problem, solution works

**Comment by danielcompton** [comment]
@swannodette it may be good to do development on a `develop` branch, so when people read the README on `master`, they only see released features.

**Comment by swannodette** [comment]
Addressed now that there is a new release.
