### ISSUE TITLE
/scripts/repl.clj malformed call to repl/repl*

### ISSUE THREAD

**Issue by cmccloud** [swannodette/mies#33]
Howdy,

Running the script as is throws an ArityException. 
I was able to get it to run by either:
1) Including an empty hashmap as the second argument to repl/repl*
2) changing the call to (repl/repl (node/repl-env))

Thanks so much for all the work!

**Comment by pstephens** [comment]
I'm hitting this problem also:

pstephens@ubuntu:~/src/hello-world$ ./scripts/repl
Exception in thread "main" clojure.lang.ArityException: Wrong number of args (1) passed to: repl/repl*, compiling:(/home/pstephens/src/hello-world/scripts/repl.clj:5:1)

Working up a quick PR now.

**Comment by mneise** [comment]
This has been fixed with https://github.com/swannodette/mies/pull/35. Thank you :smiley:
