### ISSUE TITLE
rlwrap: command not found

### ISSUE THREAD

**Issue by sudodoki** [swannodette/mies#40]
>$ scripts/watch

```scripts/watch: line 2: rlwrap: command not found```

OS X 10.11.2
Fixed for my setup by running `brew install rlwrap`.

**Comment by sudodoki** [comment]
Could possibly just link to `scripts/README.md`

**Comment by mneise** [comment]
Thank you for pointing this out. Added a hint to both READMEs.

**Comment by sudodoki** [comment]
Thanks :tada:
