### ISSUE TITLE
Old source being pulled in from target/classes

### ISSUE THREAD

**Issue by kennytilton** [swannodette/mies#49]
I was stumped by an old version of code from a second repo running, even after lein clean and confirming the clojars version of the second repo was at least being pulled down during scripts/build. 

I finally figured out that the old code was being found it in target/classes, ignoring the version on clojars. Does the target directory need to be on the "clean-targets" list.

I am sure I created this mess, mind you. I was using symlinks in the checkouts directory, or perhaps these files were created when the separate repos were all part of the problematic repo -- I started that way then split things out into separate repos.

But would there be any harm in zapping target on a lein clean under this template?

**Comment by mneise** [comment]
Added the `:target-path` to `:clean-targets` with the newest release.
