### ISSUE TITLE
Issue with dot in project name

### ISSUE THREAD

**Issue by AlBaker** [swannodette/mies#6]
There's something going on in the project.clj file generated by mies.  On Windows 7, run "create new mies tester.cljs"

The resulting project.clj file then has the resulting error when attempting to be compiled:

Caused by: java.lang.RuntimeException: Unsupported escape character: \c, compiling:(c:\workspaces\ws.clj\tester.cljs\project.clj:16:37)

Looks like the output-dir results in an escape character, e.g.:

tester\cljs.js

**Comment by swannodette** [comment]
@AlBaker this just seems like an edge case in template generation itself. I would avoid using `.` in project names.
